# Spring Boot 3.x Configuration for FileServer
spring:
  application:
    name: fileserver

  # Allow bean definition overriding
  main:
    allow-bean-definition-overriding: true
  
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.19:3306/fileserver?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&connectTimeout=60000&socketTimeout=60000
    username: root
    password: Nstr.234808
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: FileServerHikariCP
  
  # MyBatis Configuration
  mybatis:
    mapper-locations: classpath:org/mybatis/mapper/*.xml
    type-aliases-package: net.cactus.pojo
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazy-loading-enabled: true
      multiple-result-sets-enabled: true
      use-column-label: true
      use-generated-keys: true
      auto-mapping-behavior: partial
      auto-mapping-unknown-column-behavior: warning
      default-executor-type: simple
      default-statement-timeout: 25
      default-fetch-size: 100
      safe-row-bounds-enabled: false
      safe-result-handler-enabled: true
      local-cache-scope: session
      jdbc-type-for-null: other
      lazy-load-trigger-methods: equals,clone,hashCode,toString
      default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
      call-setters-on-nulls: false
      return-instance-for-empty-row: false
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  
  # Web Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 1800MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}
  
  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# Server Configuration
server:
  port: 9101
  address: localhost
  servlet:
    context-path: /
  jetty:
    connection-idle-timeout: 1200000ms
    max-http-form-post-size: 200MB
    threads:
      max: 200
      min: 8
      idle-timeout: 60000ms
    accesslog:
      enabled: false

cactus:
  info:
    base-package: net.cactus


# Application Specific Configuration
fileserver:
  filestore: ./filestore/
  serverhost: localhost
  serverport: 9100
  
# Management Endpoints (for health check)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true
